export const SEO_KEYWORDS = [
  // --- SPANISH (Core) ---
  "impuesto matriculación coche españa",
  "calcular impuesto matriculación",
  "importar coche alemania a españa",
  "tramites importar coche",
  "cuanto cuesta matricular coche extranjero",
  "calculadora impuestos coche",
  "impuesto co2 coches",
  "tabla hacienda coches 2024",
  "valor fiscal vehiculos boe",
  "matricular coche frances en españa",
  "coste matricular coche belgica",
  "importar coche holanda",
  "impuesto transmisiones patrimoniales coche",
  "dgt matriculación",
  "itv coche importacion",
  "placas verdes dgt precio",
  "gestoria importar coche",
  "ahorro importar coche alemania",
  "mejores coches para importar",
  "impuesto circulacion ayuntamiento",
  "modelo 576 aeat",
  "modelo 620 aeat",
  "impuesto matriculacion coche electrico",
  "impuesto matriculacion hibrido enchufable",
  "exencion impuesto matriculacion",
  "familia numerosa impuesto coche",
  "discapacidad impuesto matriculacion",
  "cambio residencia coche españa",
  "baja consular coche",
  "ficha tecnica reducida precio",
  "certificado conformidad coc",
  "pasar itv coche aleman",
  "permiso circulacion temporal",
  "seguro coche matricula extranjera",
  "impuesto especial sobre determinados medios de transporte",
  "valor venal coche hacienda",
  "tablas ganvam 2024",
  "calculadora importacion coches",
  "gastos traer coche alemania",
  "guia importar coche",
  "consejos comprar coche alemania",
  "fraude kilometros coches alemania",
  "garantia coche importado",
  "iva intracomunitario coches",
  "comprar coche neto exportacion",

  // --- ENGLISH (Expats/Tourists) ---
  "import car to spain tax calculator",
  "register uk car in spain cost",
  "car registration tax spain",
  "import vehicle from germany to spain",
  "spanish matriculation tax calculator",
  "cost of re-registering car in spain",
  "bring car to spain residency",
  "spanish license plates cost",
  "itv spain foreign car",
  "buy car in germany bring to spain",
  "import duty car spain",
  "non-resident car spain 6 months",
  "registering eu car in spain",
  "car import taxes spain calculator",
  "change uk plates to spanish",
  "driving foreign car in spain residents",
  "special tax on certain means of transport spain",
  "fiscal value car spain",
  "co2 emissions tax spain car",
  "electric car import tax spain",
  "hybrid car registration tax spain",
  "green plates spain price",
  "temporary license plates spain",
  "spanish customs car import",
  "residency exemption car tax spain",
  "torrevieja car registration",
  "malaga car import service",
  "alicante register foreign car",
  "madrid car import taxes",
  "barcelona vehicle registration cost",
  "valencia import car tax",
  "marbella luxury car import",

  // --- GERMAN (Major Market) ---
  "auto nach spanien importieren kosten",
  "kfz zulassungssteuer spanien rechner",
  "auto ummelden spanien kosten",
  "spanisches kennzeichen beantragen",
  "auto einführen spanien als resident",
  "co2 steuer auto spanien",
  "deutsche zulassung in spanien fahren",
  "auto in spanien anmelden",
  "tüv spanien für deutsche autos",
  "auswandern spanien auto mitnehmen",
  "spanische zulassungssteuer tabelle",
  "auto überführen nach spanien",

  // --- FRENCH (Major Neighbor) ---
  "immatriculer voiture française en espagne",
  "calcul taxe immatriculation espagne",
  "importation voiture france espagne",
  "cout changement plaque immatriculation espagne",
  "taxe co2 voiture espagne",
  "ramener voiture en espagne",
  "nie voiture espagne",
  " ITV voiture française",

  // --- DUTCH (Significant Expat Community) ---
  "auto invoeren spanje kosten",
  "auto op spaans kenteken zetten",
  "wegenbelasting spanje berekenen",
  "auto meenemen naar spanje emigreren",

  // --- SPECIFIC BRANDS/MODELS (High Volume) ---
  "importar mercedes alemania impuestos",
  "importar bmw alemania impuestos",
  "importar audi alemania impuestos",
  "importar volkswagen alemania impuestos",
  "importar porsche alemania impuestos",
  "import tesla to spain tax",
  "matriculacion camper españa precio",
  "homologar furgoneta vivienda españa",
];
