// Per-car SEO content. The KEY of each entry must match the route slug
// generated by `slugify("${brand}-${modelQuery}")` in src/utils/seo/topCars.ts.
// Examples: "volkswagen-golf", "bmw-serie-3", "mercedes-benz-clase-c".
//
// When a slug has no entry here, CarPageContent gracefully hides the
// unique-paragraph / FAQ / related-cars sections. Fill in entries as you write
// content — pages get stronger as you go.

export type CarFaq = { question: string; answer: string };

export type CarContent = {
  // 100+ word paragraph specific to this model: typical Spanish import volume,
  // common origin country, market notes, ZBE/etiqueta DGT considerations, etc.
  uniqueParagraph: string;
  // 3–4 FAQ entries with model-specific answers. Empty array hides the section.
  faq: CarFaq[];
  // Where most imports of this model originate (e.g. "Alemania", "Países Bajos").
  commonOrigin: string;
  // Optional related model slugs to surface in the "Related cars" grid.
  relatedSlugs?: string[];
};

export const CARS: Record<string, CarContent> = {
  // ─── Volkswagen ──────────────────────────────────────────────────────────
  "volkswagen-golf": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Volkswagen Golf es, con diferencia, el coche más importado a España desde Alemania. Su combinación de fiabilidad alemana, mecánica accesible y un mercado de segunda mano enorme lo convierte en la opción favorita para quienes quieren importar un compacto. La séptima y octava generación (Golf VII y VIII) dominan las búsquedas en AutoScout24 y Mobile.de, con precios entre 8.000 € y 22.000 € según motorización y kilometraje. Para los Golf GTI y R, el valor BOE es notablemente más alto, lo que aumenta el ITP y el IEDMT a pagar. Importante: los Golf TDI (diésel) suelen tener etiqueta DGT C — verifica que el modelo cumpla la normativa Euro 6 antes de comprarlo, especialmente si vas a circular en Madrid, Barcelona o cualquier ciudad con Zona de Bajas Emisiones (ZBE).",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Volkswagen Golf desde Alemania a España?",
        answer:
          "El coste total depende del precio de compra y la edad del coche. Para un Golf de 15.000 € con 3 años, calcula aproximadamente: 600–900 € de ITP (según comunidad), 0–500 € de IEDMT (depende del CO₂), 800–1.200 € de transporte y unos 300–500 € de gestoría y ITV. Total estimado: 17.000–18.500 € puesto en España.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un Golf importado?",
        answer:
          "Los Golf gasolina post-2014 (Euro 6) tienen etiqueta C, los Golf TDI 2016+ también suelen ser C. Los Golf GTE (híbrido enchufable) tienen etiqueta CERO o ECO. Los Golf diésel anteriores a 2015 con Euro 5 tendrán etiqueta B y estarán restringidos en muchas ZBE. Verifica siempre la fecha de matriculación original y la norma Euro en el certificado COC.",
      },
      {
        question: "¿Es mejor importar un Golf TSI o TDI a España?",
        answer:
          "Depende del uso. Los Golf TSI (gasolina) tienen menor IEDMT por sus emisiones más bajas en motores pequeños, mejor etiqueta DGT y menos restricciones en ciudades. Los TDI son más eficientes para autopista pero pueden tener problemas de homologación en versiones antiguas y menor valor de reventa en España por las restricciones del diésel.",
      },
      {
        question: "¿Qué documentación necesito para importar un Golf desde Alemania?",
        answer:
          "Necesitarás: el COC (Certificado de Conformidad europeo), la Fahrzeugbrief (ficha técnica alemana), el contrato de compra-venta firmado, factura con IVA si compras a profesional, y baja temporal o definitiva en Alemania. Con esos documentos podrás pasar la ITV de importación en España y completar la matriculación.",
      },
    ],
    relatedSlugs: ["volkswagen-polo", "volkswagen-tiguan", "audi-a3"],
  },

  "volkswagen-polo": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Volkswagen Polo es uno de los utilitarios más importados a España, especialmente para quienes buscan un primer coche o un segundo vehículo urbano con fiabilidad alemana. La generación AW (Polo VI, 2017–presente) y la GP (Polo V facelift) son las más habituales en el mercado alemán de ocasión, con precios entre 7.000 € y 14.000 €. El Polo GTI (200 cv) es la versión deportiva más buscada y tiene un valor BOE significativamente más alto. Al ser un coche pequeño con motores TSI de 1.0 o 1.6 litros, las emisiones de CO₂ suelen estar por debajo de 120 g/km, lo que normalmente exime al Polo del IEDMT — un ahorro de varios miles de euros frente a importar un Tiguan o Passat. Esa exención fiscal es probablemente el mayor atractivo del Polo como importación.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Volkswagen Polo a España?",
        answer:
          "Para un Polo de 12.000 € con 3 años, calcula: 480–720 € de ITP (4–6% según comunidad), normalmente 0 € de IEDMT (por bajas emisiones), 800–1.000 € de transporte desde Alemania, y unos 300–400 € de gestoría e ITV. Total estimado: 13.600–14.100 € matriculado.",
      },
      {
        question: "¿Paga IEDMT un Polo importado?",
        answer:
          "La mayoría no. Los Polo TSI 1.0 y 1.6 emiten entre 105–119 g/km de CO₂, lo que los sitúa en el tramo del 0% de IEDMT. Solo el Polo GTI (con motor 2.0 TSI) supera los 150 g/km y paga IEDMT del 4,75%. Verifica las emisiones exactas en el COC antes de comprar.",
      },
      {
        question: "¿El Polo tiene etiqueta ECO o C?",
        answer:
          "Los Polo gasolina post-2017 tienen etiqueta C (Euro 6). Solo los Polo TGI (gas natural comprimido, GNC) tienen etiqueta ECO. No hay versión híbrida enchufable del Polo, así que no esperes etiqueta CERO. Esto significa restricciones de circulación en algunas ZBE estrictas como Madrid Central.",
      },
      {
        question: "¿Merece la pena importar un Polo desde Alemania?",
        answer:
          "Solo si encuentras una versión bien equipada (R-Line, Beats, GTI) a un precio significativamente inferior al español. Para Polo base, las diferencias de precio suelen ser pequeñas (1.000–2.000 €) y el coste de transporte e impuestos puede neutralizar el ahorro. Es más rentable importar Golf, Polo GTI o Polo R-Line con kilometraje bajo.",
      },
    ],
    relatedSlugs: ["volkswagen-golf", "audi-a3", "mercedes-benz-clase-a"],
  },

  "volkswagen-tiguan": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Volkswagen Tiguan es el SUV compacto más vendido de Europa y uno de los favoritos en el mercado de importación español. La segunda generación (5N facelift) y la tercera (BW, 2024+) dominan AutoScout24 y Mobile.de con precios entre 18.000 € y 38.000 € según motorización y equipamiento. Las versiones R-Line y Allspace (7 plazas, 4,72 m) son las más buscadas por familias. Importante: muchos Tiguan TDI de 150 cv superan los 145 g/km de CO₂, entrando en el tramo del 4,75% de IEDMT, lo que suma 600–1.200 € adicionales al coste de importación. El Tiguan eHybrid (PHEV) tiene etiqueta CERO y queda exento del IEDMT, lo que lo hace fiscalmente muy atractivo si encuentras una buena oferta en Alemania o Países Bajos.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Volkswagen Tiguan a España?",
        answer:
          "Para un Tiguan de 22.000 € con 3 años (versión 2.0 TDI 150 cv), calcula: 900–1.300 € de ITP, 600–1.000 € de IEDMT, 900–1.200 € de transporte desde Alemania, y unos 400–500 € de gestoría. Total estimado: 24.800–26.000 € matriculado en España.",
      },
      {
        question: "¿Cuál es el mejor Tiguan para importar?",
        answer:
          "Para minimizar impuestos, el Tiguan eHybrid (1.4 TSI + motor eléctrico) es la mejor opción: etiqueta CERO, exento de IEDMT y autonomía eléctrica de 50 km. Para uso convencional, el 2.0 TDI 150 cv 4Motion es el más buscado por su equilibrio entre potencia, consumo y valor de reventa.",
      },
      {
        question: "¿El Tiguan Allspace de 7 plazas se importa igual?",
        answer:
          "Sí, el proceso de importación es idéntico. La diferencia es que el Allspace suele tener un valor BOE algo más alto (entre 1.500 € y 3.000 € más que el Tiguan estándar), lo que aumenta proporcionalmente el ITP. Es muy buena opción para familias que necesitan 7 plazas con presupuesto inferior al de un X5.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un Tiguan importado?",
        answer:
          "Los Tiguan TSI gasolina post-2017 tienen etiqueta C. Los TDI 2.0 Euro 6d tienen etiqueta C. Los Tiguan eHybrid (PHEV) tienen etiqueta CERO. Los Tiguan TDI anteriores a 2017 con Euro 5 tendrán etiqueta B y estarán restringidos en bastantes ZBE — evítalos si vas a usarlo en grandes ciudades.",
      },
    ],
    relatedSlugs: ["audi-q5", "bmw-x3", "mercedes-benz-glc"],
  },

  "volkswagen-passat": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Volkswagen Passat es un favorito histórico del mercado de importación español, especialmente la variante Variant (familiar/break) que apenas se vende en concesionario en España pero abunda en el mercado alemán. Las generaciones B8 (2014–2023) y B9 (2024+) son las más importadas, con precios entre 12.000 € y 32.000 €. La motorización más común es el 2.0 TDI 150 cv, muy demandada por las flotas alemanas, lo que abarata el mercado de ocasión. Las versiones Passat GTE (híbrido enchufable) y R-Line también son frecuentes en importación. Hay que tener cuidado con los Passat TDI anteriores a 2017 (Euro 5, etiqueta B) — están limitados en muchas ZBE españolas. El Passat Alltrack (versión campera con suspensión elevada) es una rareza muy buscada y casi imposible de encontrar en España nueva.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Volkswagen Passat a España?",
        answer:
          "Para un Passat Variant 2.0 TDI de 18.000 € con 4 años, calcula: 720–1.100 € de ITP, 500–800 € de IEDMT, 900–1.200 € de transporte, y unos 400–500 € de gestoría e ITV. Total estimado: 20.500–21.500 € matriculado.",
      },
      {
        question: "¿Por qué importar un Passat Variant si en España hay Passat sedán?",
        answer:
          "En España apenas se vende la versión Variant del Passat, mientras que en Alemania representa más del 70% de las ventas. Importar un Passat Variant es prácticamente la única vía de tenerlo en España, y con precios alemanes inferiores en 4.000–8.000 € a equivalentes españoles para versiones bien equipadas.",
      },
      {
        question: "¿El Passat GTE merece la pena importarlo?",
        answer:
          "Sí. El Passat GTE (híbrido enchufable, 218 cv) tiene etiqueta CERO, exención del IEDMT, autonomía eléctrica de ~55 km y un valor de reventa fuerte. Encontrarás más unidades GTE en Alemania que en España y a precios competitivos.",
      },
      {
        question: "¿Qué problemas comunes tienen los Passat TDI importados?",
        answer:
          "Los principales son: inyectores en los motores EA189 (afectados por el dieselgate), válvula EGR y filtro de partículas (DPF) saturado por uso urbano, y posibles fallos en el módulo Haldex en los 4Motion. Pide siempre el historial de servicio y un test de compresión antes de comprar.",
      },
    ],
    relatedSlugs: ["audi-a4", "bmw-serie-3", "mercedes-benz-clase-c"],
  },

  // ─── BMW ─────────────────────────────────────────────────────────────────
  "bmw-serie-1": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El BMW Serie 1 es un compacto premium con dos generaciones muy diferentes en el mercado de importación: la F20/F21 (2011–2019, propulsión trasera) y la F40 (2019–presente, tracción delantera, compartida con MINI). Los puristas buscan los F20 RWD (especialmente el M140i, último 6 cilindros tracción trasera del segmento) con precios entre 15.000 € y 32.000 €. Los F40 son más prácticos y económicos: el 118i y 120d dominan el mercado alemán de ocasión con precios entre 18.000 € y 30.000 €. El M135i xDrive (306 cv) es la versión hot hatch más buscada en importación. Importante: los Serie 1 diésel (118d, 120d) suelen tener etiqueta C, pero la familia 116d previos a 2018 tienen Euro 5 (etiqueta B) y están limitados en ZBE.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un BMW Serie 1 a España?",
        answer:
          "Para un Serie 1 de 20.000 € con 4 años (118i), calcula: 800–1.200 € de ITP, 400–700 € de IEDMT, 900–1.200 € de transporte, y unos 400–500 € de gestoría. Total estimado: 22.500–23.600 € matriculado.",
      },
      {
        question: "¿F20 o F40: cuál es mejor importar?",
        answer:
          "Si valoras la dinámica de conducción y el legado BMW, el F20 RWD (especialmente M140i o 125i) es una compra única que cada año pierde menos valor. Si buscas practicidad, mejor consumo y tecnología actual (iDrive 7/8), el F40 es la mejor opción. El M135i xDrive es el único compacto BMW con 4 ruedas motrices.",
      },
      {
        question: "¿El M135i paga mucho IEDMT al importarlo?",
        answer:
          "El M135i xDrive emite alrededor de 165–170 g/km de CO₂, lo que lo coloca en el tramo del 9,75% de IEDMT. Sobre un valor fiscal de 35.000 €, eso son aproximadamente 3.400 € de IEDMT, sumando al ITP (4–10%) y costes logísticos. Aún así suele ser 3.000–6.000 € más barato que comprarlo nuevo en España.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un Serie 1 importado?",
        answer:
          "Los Serie 1 gasolina post-2018 (Euro 6d) tienen etiqueta C. Los diésel 118d/120d 2018+ también tienen C. Los modelos pre-2018 con Euro 5 tienen etiqueta B y restricciones en ZBE como Madrid Central, BCN ZBE Rondas y Sevilla ZBE.",
      },
    ],
    relatedSlugs: ["bmw-serie-3", "audi-a3", "mercedes-benz-clase-a"],
  },

  "bmw-serie-3": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El BMW Serie 3 es el sedán premium más importado a España, con un mercado de segunda mano alemán que ofrece más unidades, mejores precios y configuraciones más completas que el mercado español. La generación G20 (2019–presente) y la F30 (2012–2019) concentran la mayoría de las importaciones. Modelos como el 320d, 330i y los M340i/M3 son habituales en AutoScout24 y Mobile.de con precios entre 18.000 € y 65.000 €. Importante: el Serie 3 suele tener un valor BOE alto, lo que se traduce en un ITP significativo (por ejemplo, 1.200 € en Madrid sobre un valor fiscal de 30.000 €). Para versiones de alta cilindrada (M3, 340i), el IEDMT por emisiones de CO₂ puede sumar varios miles de euros adicionales.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un BMW Serie 3 desde Alemania a España?",
        answer:
          "Para un Serie 3 de 25.000 € con 4 años, calcula aproximadamente: 1.000–1.500 € de ITP, 500–2.500 € de IEDMT (depende del CO₂ y de si es 320d, 330i o M340i), 900–1.300 € de transporte desde Múnich/Stuttgart, y unos 400–600 € de gestoría e ITV. Total estimado: 28.000–31.000 € matriculado en España.",
      },
      {
        question: "¿El BMW M3 paga más impuestos al importarlo?",
        answer:
          "Sí, considerablemente más. El M3 tiene emisiones de CO₂ por encima de 200 g/km, lo que lo coloca en el tramo más alto del IEDMT (14,75%). Sobre un valor fiscal de 80.000 €, el IEDMT solo puede ascender a 11.800 €. Súmale el ITP (4–10% según comunidad) y los costes logísticos, y la diferencia frente a comprarlo nuevo en España puede reducirse significativamente.",
      },
      {
        question: "¿Qué problemas comunes tienen los BMW Serie 3 importados?",
        answer:
          "Los principales puntos a revisar son: el historial de servicio (BMW Service History), posibles problemas de inyectores en motores N47 (diésel pre-2015), desgaste de la cadena de distribución en motores N20, y verificación de que el coche no haya pasado por reparaciones estructurales. Siempre pide el informe de Carfax o un equivalente alemán (Auto.de) antes de comprar.",
      },
      {
        question: "¿Puedo conducir un BMW Serie 3 importado en Madrid Central / ZBE?",
        answer:
          "Sí, siempre que tenga etiqueta DGT B, C, ECO o CERO. La mayoría de Serie 3 post-2015 (Euro 6) tienen etiqueta C. Los modelos 320e/330e híbridos enchufables tienen etiqueta CERO. Los Serie 3 diésel anteriores a 2014 con Euro 5 (etiqueta B) tienen restricciones de circulación en ciertas ZBE — verifica antes de comprar.",
      },
    ],
    relatedSlugs: ["bmw-serie-1", "bmw-x3", "audi-a4"],
  },

  "bmw-x3": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El BMW X3 es uno de los SUV premium más importados a España. La generación G01 (2017–2024) y la nueva G45 (2024+) son las dominantes en AutoScout24 y Mobile.de, con precios entre 22.000 € y 55.000 €. El X3 xDrive20d (190 cv, diésel) es la versión más común en el mercado alemán de segunda mano por su uso intensivo en flotas corporativas. El X3 M40i (360 cv) y X3 M Competition (510 cv) son las versiones de altas prestaciones más buscadas en importación. Importante: el X3 M40i emite alrededor de 200 g/km de CO₂ y el X3 M más de 240 g/km — ambos pagan el tramo máximo del IEDMT (14,75%), lo que añade entre 4.000 € y 10.000 € al coste de importación según el valor fiscal. El X3 xDrive30e (PHEV) es la única versión exenta de IEDMT.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un BMW X3 a España?",
        answer:
          "Para un X3 xDrive20d de 30.000 € con 4 años, calcula: 1.200–1.800 € de ITP, 1.500–2.500 € de IEDMT (CO₂ ~150 g/km), 900–1.300 € de transporte, y unos 500–700 € de gestoría. Total estimado: 34.000–36.000 € matriculado.",
      },
      {
        question: "¿El X3 M40i o M Competition merece la pena importarlo?",
        answer:
          "Solo si encuentras una unidad significativamente más barata que en España (descuentos de 8.000–15.000 € comunes en Alemania). El X3 M Competition paga IEDMT del 14,75% (5.000–8.000 €) y el ITP escala con su valor BOE. Pero versiones bien equipadas son raras en España, por lo que la importación sigue siendo atractiva para entusiastas.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un X3 importado?",
        answer:
          "Los X3 gasolina (xDrive30i, M40i, M) y diésel xDrive20d/30d post-2018 (Euro 6d) tienen etiqueta C. Los X3 xDrive30e (híbrido enchufable, 50 km de autonomía eléctrica) tienen etiqueta CERO. Los X3 pre-2017 con Euro 5 tienen etiqueta B y restricciones en algunas ZBE.",
      },
      {
        question: "¿Qué diferencia hay entre importar X3 y X3 M Competition?",
        answer:
          "Fiscalmente es enorme. El X3 base paga 4,75–9,75% de IEDMT (~1.500–3.000 €). El X3 M Competition tiene CO₂ >240 g/km y paga el máximo 14,75% sobre un valor BOE muy alto, llegando fácilmente a 10.000 € de IEDMT. Además el ITP escala proporcionalmente. Aún así, los descuentos del mercado alemán de altas prestaciones pueden compensarlo.",
      },
    ],
    relatedSlugs: ["bmw-x5", "audi-q5", "mercedes-benz-glc"],
  },

  "bmw-x5": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El BMW X5 es uno de los SUV grandes más importados a España, especialmente desde Alemania. Las generaciones F15 (2013–2018) y G05 (2018–presente) son las dominantes, con precios entre 28.000 € y 90.000 € según versión. El X5 xDrive30d (M57/B57, diésel 6 cilindros) es el más común; el X5 M50d/M50i y el X5 M son las versiones de altas prestaciones más demandadas. Importante: el X5 es un coche de impuestos altos en España. La mayoría de versiones diésel emiten 175–200 g/km de CO₂ (tramo 9,75% de IEDMT) y las versiones M superan los 230 g/km (tramo 14,75%). Sobre valores BOE que rondan los 60.000–80.000 €, el IEDMT puede alcanzar 8.000–12.000 €. Solo el X5 xDrive45e/50e (híbrido enchufable, >40 km autonomía eléctrica) queda exento. Pese a los impuestos, la importación de X5 sigue siendo rentable: las diferencias de precio frente al mercado español son de 8.000–20.000 €.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un BMW X5 a España?",
        answer:
          "Para un X5 xDrive30d de 45.000 € con 4 años, calcula: 1.800–2.700 € de ITP, 3.500–5.000 € de IEDMT (CO₂ ~180 g/km), 1.000–1.400 € de transporte, y unos 600–800 € de gestoría. Total estimado: 52.000–55.000 € matriculado.",
      },
      {
        question: "¿El X5 M paga muchos impuestos al importarlo?",
        answer:
          "Sí, paga el máximo. El X5 M Competition emite ~280 g/km de CO₂, tramo del 14,75% de IEDMT. Sobre un valor BOE de 130.000 €, eso son ~19.000 € de IEDMT. Súmale 5.000–13.000 € de ITP según comunidad y los gastos logísticos. Aún así, encontrar X5 M con km bajos en Alemania puede ahorrarte 15.000–25.000 € frente al precio español.",
      },
      {
        question: "¿X5 xDrive45e (híbrido enchufable) es la opción más barata fiscalmente?",
        answer:
          "Con diferencia. El X5 xDrive45e tiene autonomía eléctrica >40 km, lo que le da etiqueta CERO y exención del IEDMT (ahorro de 4.000–8.000 € frente a un X5 diésel equivalente). Es la opción más eficiente fiscalmente, aunque su precio de partida en Alemania también es más alto.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un X5 importado?",
        answer:
          "Los X5 gasolina y diésel post-2018 (Euro 6d-temp y Euro 6d) tienen etiqueta C. Los X5 xDrive45e/50e (PHEV) tienen etiqueta CERO. Los X5 diésel pre-2017 con Euro 5 tienen etiqueta B y restricciones en ZBE como Madrid Central. Para uso urbano en grandes ciudades, mejor importar versiones 2018+ o PHEV.",
      },
    ],
    relatedSlugs: ["bmw-x3", "porsche-cayenne", "land-rover-range"],
  },

  // ─── Mercedes-Benz ───────────────────────────────────────────────────────
  "mercedes-benz-clase-a": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Mercedes-Benz Clase A es uno de los compactos premium más importados a España. La generación W177 (2018–presente) domina las búsquedas en AutoScout24 y Mobile.de con precios entre 18.000 € y 45.000 €. Las versiones A 180 d y A 200 son las más comunes en el mercado alemán de ocasión, especialmente con paquete AMG Line. El A 35 AMG (306 cv, 4MATIC) y el A 45 S AMG (421 cv, 4MATIC+) son los hot hatches más buscados en importación. La tecnología MBUX (pantallas grandes y comandos por voz) y la calidad de acabados premium son los principales atractivos. Importante: el A 45 S supera los 190 g/km de CO₂, entrando en el tramo del 9,75% de IEDMT (o 14,75% en algunas versiones), lo que suma 3.000–5.000 € al coste de importación. El A 250 e (híbrido enchufable) tiene etiqueta CERO y queda exento del IEDMT.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Mercedes Clase A a España?",
        answer:
          "Para un A 180 d de 22.000 € con 3 años, calcula: 900–1.300 € de ITP, 600–1.000 € de IEDMT, 900–1.200 € de transporte, y unos 400–500 € de gestoría. Total estimado: 24.800–26.000 € matriculado.",
      },
      {
        question: "¿Cuál es la diferencia entre A 35 AMG y A 45 S AMG fiscalmente?",
        answer:
          "El A 35 AMG (306 cv, ~170 g/km de CO₂) paga IEDMT del 9,75%. El A 45 S AMG (421 cv, ~195 g/km) puede llegar al tramo 14,75%. Sobre un valor BOE de 55.000 €, la diferencia de IEDMT puede ser de 3.000–4.000 €. El A 35 es la opción más equilibrada para importar como hot hatch.",
      },
      {
        question: "¿El Clase A 250 e es la mejor opción para evitar IEDMT?",
        answer:
          "Sí. El A 250 e (híbrido enchufable, 218 cv, autonomía eléctrica ~70 km WLTP) tiene etiqueta CERO, exención del IEDMT (ahorro de 800–1.500 €) y libre circulación en cualquier ZBE española. Es perfecto para uso urbano con desplazamientos largos ocasionales.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un Clase A importado?",
        answer:
          "Los Clase A gasolina (A 180, A 200, A 35 AMG, A 45 S) post-2018 tienen etiqueta C. Los diésel A 180 d/A 200 d post-2018 con Euro 6d también tienen C. El A 250 e (PHEV) tiene CERO. No hay Clase A 100% eléctrico — para eso busca el EQA.",
      },
    ],
    relatedSlugs: ["mercedes-benz-clase-c", "audi-a3", "bmw-serie-1"],
  },

  "mercedes-benz-clase-c": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Mercedes-Benz Clase C es uno de los sedanes premium más importados a España. La generación W205 (2014–2021) y la W206 (2021–presente) dominan el mercado, con precios entre 17.000 € y 60.000 €. El C 220 d (diésel) es la versión más común en flotas alemanas y, por tanto, en el mercado de ocasión. La variante T-Modell (estate/familiar) es muy buscada en importación porque apenas se ofrece en concesionarios españoles. El C 63 AMG (V8 biturbo en W205, híbrido enchufable de 680 cv en W206) es la versión de altas prestaciones más demandada — y la más cara fiscalmente. Importante: el C 63 W205 paga el máximo IEDMT (14,75%) por sus emisiones >240 g/km, lo que añade 7.000–12.000 € a la importación. El C 300 e (PHEV) tiene etiqueta CERO y exención de IEDMT.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Mercedes Clase C a España?",
        answer:
          "Para un C 220 d T-Modell de 28.000 € con 4 años, calcula: 1.100–1.700 € de ITP, 1.200–2.000 € de IEDMT, 900–1.300 € de transporte, y unos 500–700 € de gestoría. Total estimado: 31.700–33.700 € matriculado.",
      },
      {
        question: "¿El C 63 AMG paga mucho IEDMT al importarlo?",
        answer:
          "Sí, considerablemente. El C 63 AMG W205 (V8 4.0 biturbo, 510 cv) emite >240 g/km de CO₂, paga 14,75% de IEDMT. Sobre un valor BOE de 80.000 € son ~11.800 € de IEDMT, más el ITP. El C 63 S E Performance W206 (PHEV de 680 cv) tiene >100 km de autonomía eléctrica, etiqueta CERO y exención total de IEDMT — fiscalmente mucho más atractivo.",
      },
      {
        question: "¿Por qué importar la versión T-Modell (estate) si en España hay sedán?",
        answer:
          "En España, la versión T-Modell se vende en cantidades mínimas. En Alemania representa casi la mitad de las ventas del Clase C, lo que crea un mercado de ocasión enorme. Importar una T-Modell te permite tener una versión que casi no encuentras en España, con descuentos del 15–25% frente a unidades españolas equivalentes.",
      },
      {
        question: "¿Qué problemas comunes tienen los Clase C importados?",
        answer:
          "Los W205 pueden tener problemas de cadena de distribución en motores OM651 (diésel pre-2018), filtro de partículas saturado en diésel de uso urbano, y desgaste prematuro en suspensión Airmatic. Los W206 son demasiado nuevos para conocer problemas recurrentes. Pide siempre el historial de servicio Mercedes (Digital Service Booklet).",
      },
    ],
    relatedSlugs: ["mercedes-benz-clase-e", "bmw-serie-3", "audi-a4"],
  },

  "mercedes-benz-clase-e": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Mercedes-Benz Clase E es uno de los sedanes ejecutivos más importados a España, especialmente la versión T-Modell (estate) que es prácticamente inexistente en concesionarios españoles. Las generaciones W213 (2016–2023) y W214 (2023+) dominan el mercado de ocasión alemán, con precios entre 22.000 € y 75.000 €. El E 220 d es la motorización más común — fiable, eficiente, con buenos valores de reventa. El E 53 AMG y E 63 S AMG son los buques insignia de altas prestaciones, ambos con impuestos elevadísimos en España. El All-Terrain (versión campera con suspensión elevada) es una rareza imposible de encontrar en España nueva. Importante: los Clase E diésel pre-2018 con Euro 5 tienen etiqueta B — verifica siempre la fecha de homologación. El E 300 de (PHEV diésel) es una opción única en el segmento, con etiqueta CERO.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Mercedes Clase E a España?",
        answer:
          "Para un E 220 d T-Modell de 32.000 € con 4 años, calcula: 1.300–1.900 € de ITP, 1.500–2.500 € de IEDMT, 1.000–1.300 € de transporte, y unos 500–700 € de gestoría. Total estimado: 36.300–38.400 € matriculado.",
      },
      {
        question: "¿El Clase E All-Terrain se puede importar?",
        answer:
          "Sí, sin problemas (es un modelo homologado europeo). El All-Terrain combina la versión T-Modell con suspensión elevada (~3 cm) y tracción 4MATIC. En España no se comercializa, por lo que la importación es la única vía para tenerlo. Sus precios en Alemania rondan los 35.000–60.000 € según versión y kilometraje.",
      },
      {
        question: "¿El E 63 S AMG paga mucho IEDMT?",
        answer:
          "Sí, el máximo. Con V8 4.0 biturbo de 612 cv y CO₂ >260 g/km, paga 14,75% de IEDMT. Sobre un valor BOE de 110.000 € son ~16.200 € de IEDMT. El ITP suma otros 4.400–11.000 € según comunidad. Aún así, las diferencias de precio frente al mercado español pueden ser de 15.000–30.000 €.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un Clase E importado?",
        answer:
          "Los Clase E gasolina y diésel post-2018 (Euro 6d) tienen etiqueta C. El E 300 e (PHEV gasolina) y E 300 de (PHEV diésel) tienen etiqueta CERO. Los Clase E diésel pre-2018 con Euro 5 tienen etiqueta B con restricciones en ZBE. Para uso urbano, mejor importar versiones 2018+ o PHEV.",
      },
    ],
    relatedSlugs: ["mercedes-benz-clase-c", "bmw-serie-3", "audi-a6"],
  },

  "mercedes-benz-glc": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Mercedes-Benz GLC es uno de los SUV premium más importados a España. La primera generación X253 (2015–2022) y la nueva X254 (2022+) dominan el mercado, con precios entre 22.000 € y 65.000 €. El GLC 220 d 4MATIC es la versión más común; el GLC Coupé (con techo descendente al estilo X4/Q3 Sportback) es muy buscado en importación porque tiene un precio significativamente más alto en concesionarios españoles. El GLC 43 AMG y GLC 63 AMG son las versiones de altas prestaciones, ambas con impuestos altos en España. El GLC 300 e 4MATIC (PHEV) es una de las mejores opciones fiscalmente: etiqueta CERO, exención de IEDMT y autonomía eléctrica >100 km WLTP en la nueva X254. Importante: el GLC 63 AMG W205 (V8 biturbo) supera los 250 g/km de CO₂ y paga el máximo IEDMT (14,75%).",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Mercedes GLC a España?",
        answer:
          "Para un GLC 220 d 4MATIC de 32.000 € con 4 años, calcula: 1.300–1.900 € de ITP, 1.500–2.500 € de IEDMT, 1.000–1.400 € de transporte, y unos 500–700 € de gestoría. Total estimado: 36.300–38.500 € matriculado.",
      },
      {
        question: "¿El GLC Coupé merece la pena importarlo?",
        answer:
          "Sí, especialmente. El GLC Coupé tiene en España un sobrecoste de 4.000–7.000 € frente al GLC normal en concesionario. En Alemania la diferencia es similar pero los precios base son más bajos. Importar un GLC Coupé bien equipado puede ahorrarte 8.000–15.000 € frente a comprarlo nuevo en España.",
      },
      {
        question: "¿El GLC 300 e PHEV es la mejor opción fiscal?",
        answer:
          "Es la opción más eficiente fiscalmente. Con autonomía eléctrica WLTP >100 km en la X254, tiene etiqueta CERO, exención de IEDMT (ahorro de 2.000–4.000 €) y libre circulación en cualquier ZBE. Su precio en Alemania ronda los 45.000–60.000 € de ocasión, frente a 60.000–80.000 € en España.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un GLC importado?",
        answer:
          "Los GLC gasolina y diésel post-2018 (Euro 6d) tienen etiqueta C. Los GLC 300 e y 300 de (PHEV) tienen etiqueta CERO. Los GLC X253 pre-2018 con Euro 6c o anteriores pueden tener etiqueta B en algunos casos — verifica siempre la norma Euro en el COC.",
      },
    ],
    relatedSlugs: ["bmw-x3", "audi-q5", "porsche-cayenne"],
  },

  // ─── Audi ────────────────────────────────────────────────────────────────
  "audi-a3": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Audi A3 es el premium compacto más importado a España, hermano técnico del Volkswagen Golf pero con acabados y tecnología superiores. Las generaciones 8V (2012–2020) y 8Y (2020–presente) dominan el mercado de ocasión alemán, con precios entre 13.000 € y 38.000 €. La variante Sportback (5 puertas) representa la mayoría de las ventas; el Sedán (3 volúmenes) es menos común. El A3 35 TDI (150 cv, diésel) es la versión más buscada por fleet; los S3 (310 cv quattro) y RS 3 (400 cv quattro, 5 cilindros) son los hot hatches más demandados. Importante: el A3 40 TFSI e (PHEV) tiene etiqueta CERO y exención de IEDMT. Los A3 8V pre-2018 con motor diésel pueden tener etiqueta B (Euro 5) — evítalos para uso urbano.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Audi A3 a España?",
        answer:
          "Para un A3 Sportback 35 TDI de 22.000 € con 3 años, calcula: 900–1.300 € de ITP, 600–1.000 € de IEDMT, 900–1.200 € de transporte, y unos 400–500 € de gestoría. Total estimado: 24.800–26.000 € matriculado.",
      },
      {
        question: "¿RS 3 o S3: cuál es más rentable importar?",
        answer:
          "El S3 (310 cv) tiene CO₂ ~165 g/km y paga IEDMT del 9,75%, mientras que el RS 3 (400 cv) supera los 190 g/km y entra en el tramo 14,75%. Sobre valores BOE similares (40.000–55.000 €), el RS 3 paga 4.000–6.000 € más de IEDMT que el S3. Si lo que buscas son prestaciones de hot hatch con impuestos razonables, el S3 ofrece mejor balance.",
      },
      {
        question: "¿El A3 PHEV (40 TFSI e) es exento de IEDMT?",
        answer:
          "Sí. El A3 Sportback 40 TFSI e tiene autonomía eléctrica WLTP de ~60 km, lo que le da etiqueta CERO y exención total del IEDMT (ahorro de 1.000–1.800 €). También permite circular libremente en cualquier ZBE. Es la opción más eficiente fiscalmente para uso urbano.",
      },
      {
        question: "¿Qué problemas comunes tienen los Audi A3 importados?",
        answer:
          "Los A3 8V con motor 2.0 TDI EA189 están afectados por el dieselgate. Los TFSI 1.4 pre-2017 pueden tener consumo elevado de aceite. La caja S tronic (DSG7) requiere mantenimiento estricto cada 60.000 km. Pide siempre el historial de servicio Audi (Audi Service History) y verifica que las llamadas a revisión del dieselgate hayan sido completadas.",
      },
    ],
    relatedSlugs: ["volkswagen-golf", "bmw-serie-1", "mercedes-benz-clase-a"],
  },

  "audi-a4": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Audi A4 es uno de los sedanes y familiares premium más importados a España, especialmente la versión Avant (estate) que tiene un mercado mucho más grande en Alemania que en España. La generación B9 (2015–presente) domina el mercado de ocasión del A4, con precios entre 17.000 € y 60.000 €. El A4 Avant 40 TDI quattro (190 cv) es la versión más común en flotas alemanas y, por tanto, en el mercado de ocasión. El A4 Allroad (versión campera con suspensión elevada y plásticos protectores) es una opción muy buscada en importación porque apenas se vende en España. El S4 (354 cv V6 TFSI o 347 cv V6 TDI) y RS 4 Avant (450 cv V6 biturbo) son las versiones de altas prestaciones más demandadas. Importante: el RS 4 supera los 220 g/km de CO₂ y paga el máximo IEDMT (14,75%).",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Audi A4 a España?",
        answer:
          "Para un A4 Avant 40 TDI de 28.000 € con 4 años, calcula: 1.100–1.700 € de ITP, 1.200–2.000 € de IEDMT, 1.000–1.300 € de transporte, y unos 500–700 € de gestoría. Total estimado: 31.800–33.700 € matriculado.",
      },
      {
        question: "¿El A4 Allroad se importa igual que un A4 normal?",
        answer:
          "Sí, exactamente igual (es un modelo homologado europeo). El A4 Allroad combina la versión Avant con suspensión elevada (~34 mm), plásticos protectores y tracción quattro permanente. En España casi no se comercializa, por lo que la importación es la vía más práctica. Precios en Alemania: 30.000–50.000 € según km y equipamiento.",
      },
      {
        question: "¿Por qué importar A4 Avant si en España existe el A4 sedán?",
        answer:
          "En España el A4 Avant representa un porcentaje mínimo de las ventas (10–15%), mientras que en Alemania supera el 60%. Importar un A4 Avant te permite acceder a más unidades, mejores acabados y descuentos de 4.000–10.000 € frente a unidades españolas equivalentes — además de tener una versión rara que mantendrá mejor su valor.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un Audi A4 importado?",
        answer:
          "Los A4 gasolina y diésel post-2018 (Euro 6d) tienen etiqueta C. No hay versión PHEV del A4 (para PHEV en este segmento mira A6 o Q5). Los A4 diésel pre-2017 con Euro 5 tienen etiqueta B y restricciones en ZBE. Evita versiones antiguas para uso urbano.",
      },
    ],
    relatedSlugs: ["audi-a6", "bmw-serie-3", "mercedes-benz-clase-c"],
  },

  "audi-a6": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Audi A6 es uno de los sedanes ejecutivos más importados a España, especialmente la versión Avant que apenas se ofrece en concesionarios españoles. Las generaciones C7 (2011–2018) y C8 (2018–presente) dominan el mercado, con precios entre 20.000 € y 90.000 €. El A6 40 TDI (204 cv) y 45 TDI quattro (231 cv) son las motorizaciones más comunes en flotas alemanas. El A6 Avant es la versión más demandada en importación — apenas se ven en concesionarios españoles, pero abundan en AutoScout24 y Mobile.de con configuraciones premium. El S6 Avant (V6 TDI híbrido suave de 344 cv) y RS 6 Avant (V8 biturbo de 600 cv) son los buques insignia de altas prestaciones — el RS 6 Avant es uno de los modelos de importación más codiciados por su escasez en España y diferencia de precio (>20.000 € frente a comprarlo nuevo).",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Audi A6 a España?",
        answer:
          "Para un A6 Avant 40 TDI de 35.000 € con 4 años, calcula: 1.400–2.100 € de ITP, 1.700–2.800 € de IEDMT, 1.000–1.400 € de transporte, y unos 500–700 € de gestoría. Total estimado: 39.600–42.000 € matriculado.",
      },
      {
        question: "¿El RS 6 Avant merece la pena importarlo a España?",
        answer:
          "Sí, es uno de los modelos donde la importación más sentido tiene. El RS 6 C8 nuevo en España cuesta 150.000–180.000 €, mientras que en Alemania puedes encontrar unidades de 1–3 años por 95.000–125.000 €. Aunque paga el máximo IEDMT (14,75%, ~16.000 € sobre valor BOE ~110.000 €) y un ITP alto, el ahorro neto suele rondar los 15.000–30.000 €.",
      },
      {
        question: "¿El A6 50 TFSI e PHEV es exento de IEDMT?",
        answer:
          "Sí, si su autonomía eléctrica WLTP supera los 40 km (la mayoría de las versiones lo cumplen). Tiene etiqueta CERO, exención del IEDMT y libre circulación en ZBE. Es una opción muy eficiente fiscalmente, especialmente para uso ejecutivo con desplazamientos urbanos diarios.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un A6 importado?",
        answer:
          "Los A6 gasolina y diésel post-2018 (Euro 6d) tienen etiqueta C. Los A6 50 TFSI e (PHEV) tienen etiqueta CERO. Los A6 C7 pre-2018 con Euro 5/6b pueden tener etiqueta B — evítalos para uso urbano frecuente en ciudades con ZBE estricta.",
      },
    ],
    relatedSlugs: ["audi-a4", "bmw-serie-3", "mercedes-benz-clase-e"],
  },

  "audi-q5": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Audi Q5 es uno de los SUV premium más importados a España. La segunda generación FY (2017–presente, con facelift en 2020) y la nueva tercera generación dominan el mercado, con precios entre 22.000 € y 60.000 €. El Q5 40 TDI quattro (204 cv) es la versión más común en el mercado alemán de ocasión. El Q5 Sportback (con techo descendente) y el SQ5 (354 cv TFSI o 341 cv TDI híbrido suave) son las versiones más demandadas en importación. El Q5 55 TFSI e (PHEV de 367 cv) es una de las mejores opciones fiscalmente: etiqueta CERO, exención de IEDMT y autonomía eléctrica de ~55 km. Importante: el Q5 tiene un valor BOE alto, lo que significa un ITP significativo — 1.500–2.500 € según comunidad sobre un valor fiscal de 35.000 €.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Audi Q5 a España?",
        answer:
          "Para un Q5 40 TDI quattro de 30.000 € con 4 años, calcula: 1.200–1.800 € de ITP, 1.500–2.500 € de IEDMT, 1.000–1.300 € de transporte, y unos 500–700 € de gestoría. Total estimado: 34.200–36.300 € matriculado.",
      },
      {
        question: "¿Q5 Sportback o Q5 normal: cuál importar?",
        answer:
          "El Q5 Sportback tiene en España un sobrecoste de 3.000–5.000 € frente al Q5 estándar. En Alemania la diferencia es similar, pero la mayor oferta de ocasión permite encontrar unidades Sportback con descuentos significativos. Si te gusta la estética coupé y tienes flexibilidad en altura interior, el Sportback es una buena importación; si necesitas máximo espacio, mejor el Q5 estándar.",
      },
      {
        question: "¿El SQ5 TDI sigue siendo una buena importación?",
        answer:
          "Sí. El SQ5 TDI (341 cv, V6 con turbo eléctrico) emite ~190 g/km de CO₂, paga IEDMT del 9,75%. Sobre un valor BOE de 50.000 €, son ~4.900 € de IEDMT. Aún con esos impuestos, importar un SQ5 desde Alemania suele ahorrar 6.000–12.000 € frente al precio español, especialmente con km bajo y equipamiento completo.",
      },
      {
        question: "¿El Q5 55 TFSI e PHEV es la mejor opción fiscal?",
        answer:
          "Es la opción más eficiente fiscalmente del segmento. Con autonomía eléctrica WLTP de ~55 km tiene etiqueta CERO, exención de IEDMT (ahorro de 2.000–4.000 € frente a un Q5 diésel) y libre circulación en cualquier ZBE. Precios de ocasión en Alemania: 38.000–55.000 €.",
      },
    ],
    relatedSlugs: ["bmw-x3", "mercedes-benz-glc", "volkswagen-tiguan"],
  },

  // ─── Porsche ─────────────────────────────────────────────────────────────
  "porsche-911": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Porsche 911 es uno de los deportivos más codiciados en el mercado de importación español. Las generaciones 991 (2011–2019) y 992 (2019–presente) dominan AutoScout24 y Mobile.de, con precios entre 60.000 € y 220.000 € según versión y año. Las versiones Carrera y Carrera S son las más comunes; los Turbo, Turbo S, GT3 y GT3 RS son las más buscadas pero también las más caras fiscalmente. Importante: la mayoría de versiones 911 emiten entre 200 y 280 g/km de CO₂, lo que las coloca en el tramo máximo del IEDMT (14,75%). Sobre valores BOE típicos de 80.000–180.000 €, el IEDMT puede ascender a 12.000–26.000 €. A pesar de los impuestos, el 911 sigue siendo una importación muy rentable: las diferencias de precio frente al mercado español (donde la oferta de ocasión es limitada) pueden ser de 15.000–40.000 €. Coches de fin de semana, no de uso diario.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Porsche 911 a España?",
        answer:
          "Para un 911 Carrera S 992 de 110.000 € con 3 años, calcula: 4.400–6.600 € de ITP, 13.000–16.000 € de IEDMT, 1.200–1.800 € de transporte, y unos 800–1.200 € de gestoría. Total estimado: 129.000–135.000 € matriculado. Sigue siendo 15.000–25.000 € más barato que comprarlo nuevo en España.",
      },
      {
        question: "¿El 911 GT3 paga más impuestos que un Turbo?",
        answer:
          "Sí, ligeramente. El GT3 (atmosférico 4.0, 510 cv) emite ~290 g/km de CO₂. El Turbo S (3.8 biturbo, 650 cv) emite ~270 g/km. Ambos están en el tramo máximo del IEDMT (14,75%), pero el GT3 puede tener un valor BOE más alto en versiones recientes. Diferencia neta de IEDMT entre GT3 y Turbo S: 500–2.000 €.",
      },
      {
        question: "¿Qué documentación adicional necesito para importar un 911?",
        answer:
          "Lo habitual: COC (Certificado de Conformidad), Fahrzeugbrief alemana, factura de compra, baja en Alemania. Para deportivos con modificaciones (escape, suspensión), verifica que estén homologadas en el COC o tendrás problemas en la ITV de importación. Para versiones GT3/GT3 RS que hayan competido en circuito, asegúrate de que conserven homologación de calle válida (no la versión Cup, que es solo para pista).",
      },
      {
        question: "¿El 911 GT3 RS es matriculable en España?",
        answer:
          "Sí, todas las versiones de calle del 911 (incluido GT3 RS) son matriculables en España siempre que tengan COC válido. Solo las versiones de circuito puro (911 GT2 RS Clubsport, 911 Cup) no tienen homologación de calle. Verifica siempre el COC antes de comprar.",
      },
    ],
    relatedSlugs: ["porsche-cayenne", "bmw-serie-3", "audi-a6"],
  },

  "porsche-cayenne": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Porsche Cayenne es uno de los SUV de altas prestaciones más importados a España. Las generaciones 92A (2010–2018) y la actual PO536 (2018–presente, facelift 2023) dominan el mercado, con precios entre 25.000 € y 120.000 €. El Cayenne diésel (descontinuado tras el dieselgate) es muy buscado en mercado de ocasión por su consumo razonable y precios bajos. Las versiones Turbo (V8 biturbo de 550–650 cv) y Turbo GT son las de altas prestaciones más demandadas pero también las más caras fiscalmente. Importante: la mayoría de versiones Cayenne emiten >200 g/km de CO₂, tramo máximo del IEDMT (14,75%). El Cayenne E-Hybrid y Turbo E-Hybrid (PHEV con autonomía eléctrica >40 km WLTP) son las únicas versiones exentas — y posiblemente las opciones fiscales más inteligentes para importar.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Porsche Cayenne a España?",
        answer:
          "Para un Cayenne 3.0 V6 de 45.000 € con 4 años, calcula: 1.800–2.700 € de ITP, 5.000–7.000 € de IEDMT, 1.100–1.500 € de transporte, y unos 600–800 € de gestoría. Total estimado: 53.500–57.000 € matriculado.",
      },
      {
        question: "¿El Cayenne E-Hybrid es exento de IEDMT?",
        answer:
          "Sí. El Cayenne E-Hybrid y Turbo E-Hybrid tienen autonomía eléctrica WLTP >40 km, lo que les da etiqueta CERO y exención total del IEDMT (ahorro de 6.000–15.000 € frente a una versión gasolina equivalente). Su precio en Alemania ronda los 55.000–90.000 € de ocasión, frente a 75.000–120.000 € en España.",
      },
      {
        question: "¿El Cayenne Turbo GT paga el máximo IEDMT?",
        answer:
          "Sí. El Turbo GT (V8 biturbo, 640 cv) emite ~290 g/km de CO₂, paga 14,75% de IEDMT. Sobre un valor BOE de 130.000 € son ~19.200 € de IEDMT, más ITP de 5.200–13.000 € según comunidad. Aún así, las diferencias de precio frente al mercado español pueden alcanzar 20.000–35.000 € en versiones bien equipadas.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un Cayenne importado?",
        answer:
          "Los Cayenne gasolina y diésel post-2018 (Euro 6d) tienen etiqueta C. Los Cayenne E-Hybrid (PHEV) tienen etiqueta CERO. Los Cayenne 92A diésel pre-2018 pueden tener etiqueta B con restricciones en ZBE. Para uso urbano frecuente, mejor versiones 2018+ o PHEV.",
      },
    ],
    relatedSlugs: ["bmw-x5", "land-rover-range", "audi-q5"],
  },

  // ─── Otros ───────────────────────────────────────────────────────────────
  "toyota-rav4": {
    commonOrigin: "Países Bajos",
    uniqueParagraph:
      "El Toyota RAV4 es uno de los SUV híbridos más importados a España, especialmente la quinta generación (XA50, 2018–presente). Países Bajos y Bélgica son el origen más común — Toyota fabrica el RAV4 con configuraciones más completas para los mercados del norte de Europa, donde los precios de ocasión son significativamente inferiores a los españoles. Los precios oscilan entre 22.000 € y 45.000 € según versión y kilometraje. El RAV4 Hybrid (HEV de 218 cv) representa más del 90% de las ventas y es la versión más demandada en importación. El RAV4 Plug-in Hybrid (PHEV de 306 cv, autonomía eléctrica >70 km WLTP) es una de las mejores opciones fiscalmente: etiqueta CERO, exención de IEDMT y libre circulación en ZBE. Importante: el RAV4 Hybrid normal tiene etiqueta ECO (no CERO), y aunque paga 0% de IEDMT por sus bajas emisiones (<120 g/km), tiene restricciones en algunas ZBE estrictas.",
    faq: [
      {
        question: "¿Cuánto cuesta importar un Toyota RAV4 a España?",
        answer:
          "Para un RAV4 Hybrid de 28.000 € con 3 años, calcula: 1.100–1.700 € de ITP, normalmente 0 € de IEDMT (por bajas emisiones), 900–1.300 € de transporte desde Países Bajos, y unos 400–500 € de gestoría. Total estimado: 30.500–31.500 € matriculado.",
      },
      {
        question: "¿RAV4 Hybrid o RAV4 PHEV: cuál importar?",
        answer:
          "El RAV4 Hybrid (218 cv) tiene etiqueta ECO, paga 0 € de IEDMT y es más barato de compra. El RAV4 PHEV (306 cv, autonomía 70+ km eléctricos) tiene etiqueta CERO y mejor reventa, pero cuesta 8.000–12.000 € más en compra. Si haces muchos km urbanos, el PHEV compensa por el ahorro en combustible y libre circulación en ZBE.",
      },
      {
        question: "¿Por qué importar un RAV4 si Toyota está bien implantado en España?",
        answer:
          "Por configuraciones y precio. En Países Bajos y Bélgica, el RAV4 se vende con paquetes premium (cuero, navegación, JBL, techo panorámico) que en España son opciones caras. Además, los precios de ocasión holandeses son 2.000–5.000 € más bajos para equivalentes con km similar. Para un RAV4 PHEV equipado, el ahorro puede ser de 6.000–10.000 €.",
      },
      {
        question: "¿Qué etiqueta DGT tiene un RAV4 importado?",
        answer:
          "El RAV4 Hybrid tiene etiqueta ECO (híbrido autorrecargable). El RAV4 PHEV tiene etiqueta CERO. Los RAV4 anteriores (2016–2018, motores diésel 2.2 D-4D) tienen etiqueta C. La mayoría de RAV4 importados modernos no tienen problemas en ZBE, pero verifica siempre la etiqueta en el COC.",
      },
    ],
    relatedSlugs: ["volkswagen-tiguan", "audi-q5", "bmw-x3"],
  },

  "land-rover-range": {
    commonOrigin: "Alemania",
    uniqueParagraph:
      "El Range Rover es el SUV de lujo más codiciado en el mercado de importación español. Las generaciones L405 (2012–2021) y L460 (2022+) son las más buscadas, con precios entre 35.000 € y 180.000 € según versión y año. ⚠️ Importante: tras el Brexit, importar un Range Rover desde Reino Unido se considera una importación de país NO-UE, lo que implica arancel aduanero del 10% e IVA del 21% sobre el valor total (precio + transporte + arancel) — un sobrecoste que normalmente hace inviable la importación desde UK. La mayoría de Range Rover importados a España hoy vienen de Alemania, donde el mercado de ocasión es enorme y los precios son competitivos. El Range Rover Sport SVR y Range Rover SV (V8 biturbo, >200 g/km de CO₂) pagan el máximo IEDMT (14,75%). El Range Rover PHEV P460e/P550e (autonomía eléctrica >80 km WLTP) es la única opción exenta del IEDMT.",
    faq: [
      {
        question: "¿Puedo importar un Range Rover desde Reino Unido tras el Brexit?",
        answer:
          "Técnicamente sí, pero raramente compensa. Como Reino Unido es ahora país tercero (NO-UE), el coche paga arancel aduanero del 10% e IVA del 21% sobre el valor total (precio + transporte + arancel). Sobre un Range Rover de 50.000 €, eso son ~5.000 € de arancel + ~11.500 € de IVA. Súmale el ITP español y el IEDMT, y suele ser más caro que comprarlo en concesionario español. Mejor importar desde Alemania.",
      },
      {
        question: "¿Cuánto cuesta importar un Range Rover desde Alemania?",
        answer:
          "Para un Range Rover Vogue 3.0 D300 de 60.000 € con 4 años, calcula: 2.400–3.600 € de ITP, 7.500–10.000 € de IEDMT (CO₂ >200 g/km), 1.200–1.600 € de transporte, y unos 700–900 € de gestoría. Total estimado: 71.800–76.000 € matriculado. Diferencia frente a España: 8.000–18.000 € de ahorro.",
      },
      {
        question: "¿El Range Rover PHEV es exento de IEDMT?",
        answer:
          "Sí, las versiones P460e y P550e (PHEV con autonomía eléctrica WLTP >80 km) tienen etiqueta CERO y exención total del IEDMT (ahorro de 8.000–15.000 € frente a versiones gasolina o diésel equivalentes). Para un Range Rover de lujo, es de lejos la opción más eficiente fiscalmente.",
      },
      {
        question: "¿Qué problemas comunes tienen los Range Rover importados?",
        answer:
          "Los principales son: fallos eléctricos (módulo CCM, sensores), problemas de suspensión neumática (compresor y bolsas) tras 100.000 km, fugas en el sistema de refrigeración del V8, y desgaste prematuro de la caja ZF8. Pide siempre el historial Land Rover (Land Rover Vehicle History Report) y considera contratar una inspección pre-compra independiente — el coste de reparaciones puede ser muy alto si compras mal.",
      },
    ],
    relatedSlugs: ["porsche-cayenne", "bmw-x5", "mercedes-benz-glc"],
  },
};

export function getCarContent(slug: string): CarContent | null {
  return CARS[slug] ?? null;
}
